CREATE TABLE IF NOT EXISTS raw_sessions (
  id TEXT PRIMARY KEY,
  subscriber_id TEXT NOT NULL,
  agent_kind TEXT NOT NULL,
  agent_id TEXT NOT NULL,
  session_id TEXT NOT NULL,
  task_kind TEXT NOT NULL,
  task_summary TEXT NOT NULL,
  outcome_status TEXT NOT NULL,
  outcome_summary TEXT NOT NULL,
  input_context_summary TEXT,
  payload_json JSONB NOT NULL,
  reflection_status TEXT,
  reflection_enqueued_at TIMESTAMPTZ,
  reflection_completed_at TIMESTAMPTZ,
  reflection_error TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (subscriber_id, agent_kind, agent_id, session_id)
);
